backend = "glx";
vsync = false;
shadow = false;
fading = true;
fade-delta = 4;
inactive-opacity = 1.0;
frame-opacity = 1.0;
blur-method = "box";
blur-size = 7;
blur-background = true;
blur-background-frame = true;
blur-background-fixed = false;
opacity-rule = [
  "45:class_g = \"URxvt\"",
  "80:class_g = \"lxterminal\""
];
