#!/bin/sh

# Compositor (transparency, blur, opacity)
picom --config /home/dietpi/.config/picom/picom.conf &

# Wallpaper cycle daemon
/home/dietpi/Pictures/wallpaper-cycle.sh daemon &

# Swipe gesture daemon
/usr/local/bin/swipe-daemon &

# Load X resources for urxvt et al.
xrdb -load /home/dietpi/.Xresources

# Touch calibration (libinput affine matrix from 4-corner calibration)
xinput set-prop 6 'libinput Calibration Matrix' -0.017720 1.132511 -0.076279 -1.154947 0.046851 1.032665 0 0 1 &

# Desktop info panel (clock, date, stats, shortcuts)
/usr/local/bin/desktop-panel &
