backend = "xrender";
vsync = false;
shadow = false;
fading = true;
fade-delta = 4;
inactive-opacity = 1.0;
frame-opacity = 1.0;
blur-method = "none";
blur-background = false;
opacity-rule = [
  "70:class_g = \"URxvt\"",
  "80:class_g = \"lxterminal\""
];
